on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

id: build
name: Building and Testing

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:

      - name: Test FILE
        run: |
          cat /TEST
