on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

name: Build and Test

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:

      - name: Test FILE
        run: |
          cat /TEST
