on: pull_request_target
#on:
#  push:
#    branches:
#      - master
#  pull_request:
#    types:
#      - opened
#      - synchronize
#      - reopened

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:

#      - name: Get User Permission
#        id: checkAccess
#        uses: actions-cool/check-user-permission@v2
#        with:
#          require: write
#          username: ${{ github.triggering_actor }}
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Check User Permission
#        if: steps.checkAccess.outputs.require-result == 'false'
#        run: |
#          echo "${{ github.triggering_actor }} does not have permissions on this repo."
#          echo "Current permission level is ${{ steps.checkAccess.outputs.user-permission }}"
#          echo "Job originally triggered by ${{ github.actor }}"
#          exit 1

      - name: Check ORG SECRET
        run: |
          if [[ "x$( echo ${{ secrets.MY_SECRET }} | base64)" == "eHZhbAo=" ]]; then
            echo "Access to secrets"
          else
            echo "No access to secrets"
            exit 1
          fi

      - name: Check REPO SECRET
        run: |
          if [[ "x$( echo ${{ secrets.REPO_SECRET }} | base64)" == "eHZhbAo=" ]]; then
            echo "Access to secrets"
          else
            echo "No access to secrets"
            exit 1
          fi
